name: 'Setup releasetool'
description: 'Setup releasetool'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - run: pip install ${{ github.action_path }}
      shell: bash
